# vim: set ts=2 sts=2 sw=2 expandtab :
dist: focal
language: shell
os: linux
services:
  - docker

addons:
  apt:
    packages:
      - python3-pip
      - python3-setuptools

before_install:
  - curl -Ls -o docker-build https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/docker-build
  - chmod +x docker-build

install:
  - pip3 install PyGithub
  - ./docker-build --name ${DISTRO} --config .build.yml --install

script:
  - ./docker-build --name ${DISTRO} --verbose --config .build.yml --build scripts --build meson

notifications:
  irc:
    if: (tag OR branch = "1.24") AND
        repo = "mate-desktop/mate-desktop"
    channels:
      - "irc.freenode.org#mate-dev"
    template:
      - "[%{repository_name}] %{author}: %{commit_subject}"
      - "[%{branch}] %{commit} %{message} %{build_url}"
    on_success: never
    on_failure: always

deploy:
  - provider: script
    edge: true
    script: ./docker-build --verbose --config .build.yml --release github
    on:
      tags: true
      condition: "${TRAVIS_TAG} =~ ^v.*$ && ${DISTRO} =~ ^fedora.*$"

env:
#  - DISTRO="archlinux:latest"
  - DISTRO="debian:testing"
  - DISTRO="fedora:latest"
#  - DISTRO="ubuntu:rolling"
