# vim: set ts=2 sts=2 sw=2 expandtab :
dist: xenial
sudo: required
language: bash
services:
  - docker

branches:
  except:
  - gh-pages

before_install:
  - curl -Ls -o docker-build https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/docker-build
  - curl -Ls -o gen-index https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/gen-index.sh
  - chmod +x docker-build gen-index

install:
  - sudo apt-get install -y python3-pip python3-setuptools
  - sudo pip3 install --upgrade pip
  - sudo pip install PyGithub
  - ./docker-build --name ${DISTRO} --config .travis.yml --install

script:
  - ./docker-build --name ${DISTRO} --verbose --config .travis.yml --build scripts --build meson

deploy:
  - provider: pages
    github-token: $GITHUB_TOKEN
    #keep-history: true
    skip_cleanup: true
    committer-from-gh: true
    target-branch: gh-pages
    local-dir: html-report
    on:
      all_branches: true
      condition: ${DISTRO} =~ ^fedora.*$
  - provider: script
    script: ./docker-build --verbose --config .travis.yml --release github
    skip_cleanup: true
    on:
      tags: true
      condition: "${TRAVIS_TAG} =~ ^v.*$ && ${DISTRO} =~ ^fedora.*$"

after_success:
  - 'if [[ "$TRAVIS_SECURE_ENV_VARS" == "true" && "$TRAVIS_PULL_REQUEST" != "false" && ${DISTRO} =~ ^fedora.*$ ]]; then
        REPO_SLUG_ARRAY=(${TRAVIS_REPO_SLUG//\// });
        REPO_NAME=${REPO_SLUG_ARRAY[1]};
        URL="https://${REPO_NAME}.mate-desktop.dev";
        COMMENT="Code analysis completed";
        curl -H "Authorization: token $GITHUB_TOKEN" -X POST
           -d "{\"state\": \"success\", \"description\": \"$COMMENT\", \"context\":\"scan-build\", \"target_url\": \"$URL\"}"
           https://api.github.com/repos/${TRAVIS_REPO_SLUG}/statuses/${TRAVIS_PULL_REQUEST_SHA};
     fi'

env:
  - DISTRO="archlinux/base"
  - DISTRO="debian:testing"
  - DISTRO="fedora:30"
  - DISTRO="ubuntu:19.10"

##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/trunk?h=packages/mate-desktop
    - clang
    - gcc
    - git
    - gobject-introspection
    - gtk3
    - intltool
    - iso-codes
    - meson
    - make
    - mate-common
    - startup-notification
    - which

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/mate-desktop
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - git
    - gobject-introspection
    - gtk-doc-tools
    - intltool
    - iso-codes
    - libdconf-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libglib2.0-doc
    - libgtk-3-dev
    - libgtk-3-doc
    - libstartup-notification0-dev
    - libx11-dev
    - libxml2-dev
    - libxrandr-dev
    - mate-common
    - meson

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/mate-desktop.git
    - cairo-gobject-devel
    - clang-analyzer
    - clang
    - cppcheck-htmlreport
    - dconf-devel
    - desktop-file-utils
    - gcc
    - git
    - gobject-introspection-devel
    - gtk3-devel
    - iso-codes-devel
    - itstool
    - make
    - mate-common
    - meson
    - redhat-rpm-config
    - startup-notification-devel

  ubuntu:
    - autopoint
    - clang
    - clang-tools
    - git
    - gobject-introspection
    - gtk-doc-tools
    - intltool
    - iso-codes
    - libdconf-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libglib2.0-doc
    - libgtk-3-dev
    - libgtk-3-doc
    - libstartup-notification0-dev
    - libx11-dev
    - libxml2-dev
    - libxrandr-dev
    - mate-common
    - meson

variables:
  - CFLAGS="-Wall -Werror=format-security"
  - 'CHECKERS="
    -enable-checker deadcode.DeadStores
    -enable-checker alpha.deadcode.UnreachableCode
    -enable-checker alpha.core.CastSize
    -enable-checker alpha.core.CastToStruct
    -enable-checker alpha.core.IdenticalExpr
    -enable-checker alpha.core.SizeofPtr
    -enable-checker alpha.security.ArrayBoundV2
    -enable-checker alpha.security.MallocOverflow
    -enable-checker alpha.security.ReturnPtrRange
    -enable-checker alpha.unix.SimpleStream
    -enable-checker alpha.unix.cstring.BufferOverlap
    -enable-checker alpha.unix.cstring.NotNullTerminated
    -enable-checker alpha.unix.cstring.OutOfBounds
    -enable-checker alpha.core.FixedAddr
    -enable-checker security.insecureAPI.strcpy"'

build_scripts:
# build failed with f30 und using clang patch, fixed in f30?
#  - if [ ${DISTRO_NAME} == "fedora" ];then
#  -     curl -Ls -o fedora.sh https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/fedora.sh
#  -     bash ./fedora.sh
#  - fi
  - ./autogen.sh
  - scan-build $CHECKERS ./configure --prefix=/usr --enable-gtk-doc
  - if [ $CPU_COUNT -gt 1 ]; then
  -     scan-build $CHECKERS --keep-cc -o html-report make -j $CPU_COUNT
  - else
  -     scan-build $CHECKERS --keep-cc -o html-report make
  - fi
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     cppcheck --enable=warning,style,performance,portability,information,missingInclude .
  - fi

after_scripts:
  - if [ ${BUILD_TYPE} == "scripts" ];then
  -     if [ ${DISTRO_NAME} == "fedora" ];then
  -         cppcheck --xml --output-file=cppcheck.xml --enable=warning,style,performance,portability,information,missingInclude .
  -         cppcheck-htmlreport --title=${REPO_NAME} --file=cppcheck.xml --report-dir=cppcheck-htmlreport
  -         ./gen-index -l 20 -i https://github.com/${OWNER_NAME}/${REPO_NAME}/raw/master/icons/16x16/apps/mate-desktop.png
  -     fi
  -     make distcheck
  - fi

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: mate-desktop-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.20.0
    notify_servers:
      - https://release.mate-desktop.org/release
